services:
  dev-container:
    # https://github.com/microsoft/vscode-dev-containers/blob/main/containers/typescript-node/.devcontainer/Dockerfile
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:18-bullseye
    #ports:
    #  - "8443:8443" #port from infra-service    
  
  cloudflare:
    image: cloudflare/cloudflared
    network_mode: service:dev-container
    command:
      - tunnel
      - --metrics
      - 0.0.0.0:55555
      - --url
      - http://127.0.0.1:8787
