name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            TG_BOT_TOKEN
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      - run: curl https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/setWebhook?url=https://$(grep -m 1 BOT_URL wrangler.toml | cut -d '"' -f 2)/